<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Alumni;

class AlumniSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $alumniData = [
            [
                'nim' => '201810123456',
                'nama_lengkap' => 'Ahmad Fadillah',
                'program_studi' => 'ti',
                'tahun_lulus' => 2020,
                'email' => 'ahmad.fadillah@email.com',
                'nomor_telepon' => '+62 812-3456-7890',
                'alamat' => 'Jl. Sudirman No. 123, Jakarta Pusat',
                'pekerjaan' => 'Software Engineer',
                'perusahaan' => 'Google Indonesia',
                'jabatan' => 'Senior Software Engineer',
                'bidang_industri' => 'teknologi',
                'gaji' => 25000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Graduate 2020, Google Developer Expert',
                'kontribusi' => 'Mentoring mahasiswa TI, Memberikan beasiswa untuk mahasiswa berprestasi',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123457',
                'nama_lengkap' => 'Sarah Putri',
                'program_studi' => 'ts',
                'tahun_lulus' => 2019,
                'email' => 'sarah.putri@email.com',
                'nomor_telepon' => '+62 813-4567-8901',
                'alamat' => 'Jl. Gatot Subroto No. 456, Jakarta Selatan',
                'pekerjaan' => 'Project Manager',
                'perusahaan' => 'PT. Jaya Konstruksi',
                'jabatan' => 'Senior Project Manager',
                'bidang_industri' => 'konstruksi',
                'gaji' => 18000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Project Manager 2023, Certified PMP',
                'kontribusi' => 'Memberikan kuliah tamu, Membuka peluang magang di perusahaan',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123458',
                'nama_lengkap' => 'Budi Santoso',
                'program_studi' => 'tm',
                'tahun_lulus' => 2018,
                'email' => 'budi.santoso@email.com',
                'nomor_telepon' => '+62 814-5678-9012',
                'alamat' => 'Jl. Industri No. 789, Bekasi',
                'pekerjaan' => 'Mechanical Engineer',
                'perusahaan' => 'PT. Astra Honda Motor',
                'jabatan' => 'Senior Mechanical Engineer',
                'bidang_industri' => 'manufaktur',
                'gaji' => 15000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Innovation Award 2022, Patent Holder',
                'kontribusi' => 'Mentoring mahasiswa TM, Sharing pengalaman industri',
                'is_active' => true,
                'newsletter' => false,
            ],
            [
                'nim' => '201810123459',
                'nama_lengkap' => 'Dewi Sartika',
                'program_studi' => 'te',
                'tahun_lulus' => 2021,
                'email' => 'dewi.sartika@email.com',
                'nomor_telepon' => '+62 815-6789-0123',
                'alamat' => 'Jl. PLN No. 321, Jakarta Utara',
                'pekerjaan' => 'Electrical Engineer',
                'perusahaan' => 'PT. PLN',
                'jabatan' => 'Electrical Engineer',
                'bidang_industri' => 'energi',
                'gaji' => 12000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Graduate 2021, Energy Innovation Award',
                'kontribusi' => 'Memberikan seminar energi terbarukan',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123460',
                'nama_lengkap' => 'Nina Kartika',
                'program_studi' => 'ars',
                'tahun_lulus' => 2017,
                'email' => 'nina.kartika@email.com',
                'nomor_telepon' => '+62 816-7890-1234',
                'alamat' => 'Jl. Senayan No. 654, Jakarta Pusat',
                'pekerjaan' => 'Architect',
                'perusahaan' => 'Studio Desain Indonesia',
                'jabatan' => 'Principal Architect',
                'bidang_industri' => 'konstruksi',
                'gaji' => 20000000,
                'status_kerja' => 'wirausaha',
                'prestasi' => 'Best Design Award 2023, International Architecture Award',
                'kontribusi' => 'Membuka studio arsitektur, Memberikan workshop desain',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123461',
                'nama_lengkap' => 'Rizki Pratama',
                'program_studi' => 'ti',
                'tahun_lulus' => 2016,
                'email' => 'rizki.pratama@email.com',
                'nomor_telepon' => '+62 817-8901-2345',
                'alamat' => 'Jl. ITB No. 987, Bandung',
                'pekerjaan' => 'Dosen',
                'perusahaan' => 'Institut Teknologi Bandung',
                'jabatan' => 'Dosen & Peneliti',
                'bidang_industri' => 'pendidikan',
                'gaji' => 15000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Ph.D from MIT, Best Researcher Award 2023',
                'kontribusi' => 'Mengajar di ITB, Penelitian kolaborasi dengan Fakultas Teknik UNIMA',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123462',
                'nama_lengkap' => 'Maya Indah',
                'program_studi' => 'ptik',
                'tahun_lulus' => 2022,
                'email' => 'maya.indah@email.com',
                'nomor_telepon' => '+62 818-9012-3456',
                'alamat' => 'Jl. Pendidikan No. 147, Surabaya',
                'pekerjaan' => 'Guru',
                'perusahaan' => 'SMK Negeri 1 Surabaya',
                'jabatan' => 'Guru Produktif TI',
                'bidang_industri' => 'pendidikan',
                'gaji' => 8000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Teacher Award 2023, Certified Microsoft Educator',
                'kontribusi' => 'Mengajar di SMK, Pelatihan guru TI',
                'is_active' => true,
                'newsletter' => false,
            ],
            [
                'nim' => '201810123463',
                'nama_lengkap' => 'Andi Wijaya',
                'program_studi' => 'ptb',
                'tahun_lulus' => 2020,
                'email' => 'andi.wijaya@email.com',
                'nomor_telepon' => '+62 819-0123-4567',
                'alamat' => 'Jl. Pendidikan No. 258, Makassar',
                'pekerjaan' => 'Guru',
                'perusahaan' => 'SMK Negeri 2 Makassar',
                'jabatan' => 'Guru Produktif Bangunan',
                'bidang_industri' => 'pendidikan',
                'gaji' => 7500000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Best Teacher Award 2022, Certified AutoCAD Instructor',
                'kontribusi' => 'Mengajar di SMK, Pelatihan guru bangunan',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123464',
                'nama_lengkap' => 'Siti Nurhaliza',
                'program_studi' => 'pkk',
                'tahun_lulus' => 2021,
                'email' => 'siti.nurhaliza@email.com',
                'nomor_telepon' => '+62 820-1234-5678',
                'alamat' => 'Jl. Kesejahteraan No. 369, Yogyakarta',
                'pekerjaan' => 'Entrepreneur',
                'perusahaan' => 'Bisnis Kuliner Sehat',
                'jabatan' => 'Owner & Chef',
                'bidang_industri' => 'lainnya',
                'gaji' => 12000000,
                'status_kerja' => 'wirausaha',
                'prestasi' => 'Best Entrepreneur Award 2023, Certified Nutritionist',
                'kontribusi' => 'Membuka bisnis kuliner sehat, Pelatihan kewirausahaan',
                'is_active' => true,
                'newsletter' => true,
            ],
            [
                'nim' => '201810123465',
                'nama_lengkap' => 'Joko Widodo',
                'program_studi' => 'ts',
                'tahun_lulus' => 2015,
                'email' => 'joko.widodo@email.com',
                'nomor_telepon' => '+62 821-2345-6789',
                'alamat' => 'Jl. Merdeka No. 1, Jakarta Pusat',
                'pekerjaan' => 'Presiden',
                'perusahaan' => 'Pemerintah Republik Indonesia',
                'jabatan' => 'Presiden RI',
                'bidang_industri' => 'pemerintahan',
                'gaji' => 50000000,
                'status_kerja' => 'bekerja',
                'prestasi' => 'Presiden Republik Indonesia, Best Leader Award',
                'kontribusi' => 'Memimpin negara, Kebijakan pembangunan infrastruktur',
                'is_active' => true,
                'newsletter' => false,
            ],
        ];

        foreach ($alumniData as $data) {
            Alumni::create($data);
        }
    }
}
