<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MitraKerjasama;

class MitraKerjasamaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mitras = [
            // Perusahaan Teknologi
            [
                'nama_instansi' => 'PT Telkom Indonesia',
                'deskripsi' => 'Kerjasama dalam bidang penelitian dan pengembangan teknologi informasi dan komunikasi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Japati No.1, Bandung, Jawa Barat',
                'website' => 'https://www.telkom.co.id',
                'email' => 'ahmad.suryadi@telkom.co.id',
                'telepon' => '022-1234567',
                'logo' => 'telkom-logo.jpg',
                'tanggal_mou' => '2023-01-15',
                'tanggal_berakhir' => '2025-01-15',
                'status' => 'aktif',
                'urutan' => 1,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Indosat Ooredoo',
                'deskripsi' => 'Kerjasama dalam pengembangan aplikasi mobile dan layanan digital.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Medan Merdeka Barat No.21, Jakarta Pusat',
                'website' => 'https://www.indosatooredoo.com',
                'email' => 'hrd@indosat.com',
                'telepon' => '021-30000000',
                'logo' => 'indosat-logo.jpg',
                'tanggal_mou' => '2023-02-01',
                'tanggal_berakhir' => '2026-02-01',
                'status' => 'aktif',
                'urutan' => 2,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT XL Axiata Tbk',
                'deskripsi' => 'Kerjasama dalam pengembangan sistem informasi dan jaringan.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. H.R. Rasuna Said X5 No.13, Jakarta Selatan',
                'website' => 'https://www.xl.co.id',
                'email' => 'corporate@xl.co.id',
                'telepon' => '021-57959888',
                'logo' => 'xl-logo.jpg',
                'tanggal_mou' => '2023-03-01',
                'tanggal_berakhir' => '2025-03-01',
                'status' => 'aktif',
                'urutan' => 3,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Google Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi AI dan machine learning.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Pacific Century Place, Jakarta Selatan',
                'website' => 'https://www.google.co.id',
                'email' => 'partnership@google.com',
                'telepon' => '021-29638888',
                'logo' => 'google-logo.jpg',
                'tanggal_mou' => '2023-04-01',
                'tanggal_berakhir' => '2026-04-01',
                'status' => 'aktif',
                'urutan' => 4,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Microsoft Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan software dan cloud computing.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Pusat',
                'website' => 'https://www.microsoft.com/id-id',
                'email' => 'indonesia@microsoft.com',
                'telepon' => '021-5268888',
                'logo' => 'microsoft-logo.jpg',
                'tanggal_mou' => '2023-05-01',
                'tanggal_berakhir' => '2025-05-01',
                'status' => 'aktif',
                'urutan' => 5,
                'is_active' => true,
            ],

            // Perusahaan Energi
            [
                'nama_instansi' => 'PT PLN (Persero)',
                'deskripsi' => 'Kerjasama dalam penyelenggaraan praktik kerja lapangan untuk mahasiswa teknik elektro.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Elektro',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Trunojoyo Blok M-I No.135, Jakarta Selatan',
                'website' => 'https://www.pln.co.id',
                'email' => 'bambang.setiawan@pln.co.id',
                'telepon' => '021-7261122',
                'logo' => 'pln-logo.jpg',
                'tanggal_mou' => '2023-03-01',
                'tanggal_berakhir' => '2026-03-01',
                'status' => 'aktif',
                'urutan' => 6,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Pertamina (Persero)',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi energi terbarukan.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Medan Merdeka Timur No.1A, Jakarta Pusat',
                'website' => 'https://www.pertamina.com',
                'email' => 'corporate@pertamina.com',
                'telepon' => '021-500000',
                'logo' => 'pertamina-logo.jpg',
                'tanggal_mou' => '2023-06-01',
                'tanggal_berakhir' => '2026-06-01',
                'status' => 'aktif',
                'urutan' => 7,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Chevron Pacific Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi perminyakan.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Sudirman Kav. 1, Jakarta Pusat',
                'website' => 'https://www.chevron.com',
                'email' => 'indonesia@chevron.com',
                'telepon' => '021-5200000',
                'logo' => 'chevron-logo.jpg',
                'tanggal_mou' => '2023-07-01',
                'tanggal_berakhir' => '2025-07-01',
                'status' => 'aktif',
                'urutan' => 8,
                'is_active' => true,
            ],

            // Perusahaan Konstruksi
            [
                'nama_instansi' => 'PT Wijaya Karya (Persero)',
                'deskripsi' => 'Kerjasama dalam bidang penelitian konstruksi dan konsultasi teknik sipil.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Penelitian dan Konsultasi',
                'alamat' => 'Jl. D.I. Panjaitan Kav. 9, Jakarta Timur',
                'website' => 'https://www.wika.co.id',
                'email' => 'hendra.wijaya@wika.co.id',
                'telepon' => '021-80663388',
                'logo' => 'wika-logo.jpg',
                'tanggal_mou' => '2023-06-01',
                'tanggal_berakhir' => '2025-06-01',
                'status' => 'aktif',
                'urutan' => 9,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Pembangunan Perumahan (Persero)',
                'deskripsi' => 'Kerjasama dalam pengembangan proyek konstruksi dan infrastruktur.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Letjen TB Simatupang No.57, Jakarta Selatan',
                'website' => 'https://www.ptpp.co.id',
                'email' => 'info@ptpp.co.id',
                'telepon' => '021-78838888',
                'logo' => 'ptpp-logo.jpg',
                'tanggal_mou' => '2023-08-01',
                'tanggal_berakhir' => '2026-08-01',
                'status' => 'aktif',
                'urutan' => 10,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Adhi Karya (Persero)',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi konstruksi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Raya Pasar Minggu Km.18, Jakarta Selatan',
                'website' => 'https://www.adhi.co.id',
                'email' => 'corporate@adhi.co.id',
                'telepon' => '021-7986888',
                'logo' => 'adhi-logo.jpg',
                'tanggal_mou' => '2023-09-01',
                'tanggal_berakhir' => '2025-09-01',
                'status' => 'aktif',
                'urutan' => 11,
                'is_active' => true,
            ],

            // Perusahaan Otomotif
            [
                'nama_instansi' => 'PT Astra International Tbk',
                'deskripsi' => 'Kerjasama dalam penyelenggaraan praktik kerja lapangan untuk mahasiswa teknik mesin.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Gaya Motor Raya No.8, Jakarta Utara',
                'website' => 'https://www.astra.co.id',
                'email' => 'budi.santoso@astra.co.id',
                'telepon' => '021-50898888',
                'logo' => 'astra-logo.jpg',
                'tanggal_mou' => '2023-09-01',
                'tanggal_berakhir' => '2026-09-01',
                'status' => 'aktif',
                'urutan' => 12,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Toyota Motor Manufacturing Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi otomotif.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Laksda Yos Sudarso, Sunter, Jakarta Utara',
                'website' => 'https://www.toyota.co.id',
                'email' => 'info@toyota.co.id',
                'telepon' => '021-6510000',
                'logo' => 'toyota-logo.jpg',
                'tanggal_mou' => '2023-10-01',
                'tanggal_berakhir' => '2026-10-01',
                'status' => 'aktif',
                'urutan' => 13,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Honda Prospect Motor',
                'deskripsi' => 'Kerjasama dalam pengembangan mesin dan teknologi otomotif.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Raya Pegangsaan Dua, Jakarta Utara',
                'website' => 'https://www.honda.co.id',
                'email' => 'info@honda.co.id',
                'telepon' => '021-6400000',
                'logo' => 'honda-logo.jpg',
                'tanggal_mou' => '2023-11-01',
                'tanggal_berakhir' => '2025-11-01',
                'status' => 'aktif',
                'urutan' => 14,
                'is_active' => true,
            ],

            // Perusahaan Arsitektur
            [
                'nama_instansi' => 'PT Hadiprana Design Consultant',
                'deskripsi' => 'Kerjasama dalam pengembangan desain arsitektur dan interior.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Arsitektur',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.hadiprana.com',
                'email' => 'info@hadiprana.com',
                'telepon' => '021-5200000',
                'logo' => 'hadiprana-logo.jpg',
                'tanggal_mou' => '2023-12-01',
                'tanggal_berakhir' => '2026-12-01',
                'status' => 'aktif',
                'urutan' => 15,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Urbane Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan urban planning dan desain kota.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Arsitektur',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Sudirman Kav. 52-53, Jakarta Pusat',
                'website' => 'https://www.urbane.co.id',
                'email' => 'info@urbane.co.id',
                'telepon' => '021-5268888',
                'logo' => 'urbane-logo.jpg',
                'tanggal_mou' => '2024-01-01',
                'tanggal_berakhir' => '2027-01-01',
                'status' => 'aktif',
                'urutan' => 16,
                'is_active' => true,
            ],

            // Universitas
            [
                'nama_instansi' => 'Universitas Sam Ratulangi',
                'deskripsi' => 'Kerjasama dalam penelitian bersama dan pertukaran dosen.',
                'kategori' => 'Universitas',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Kampus Unsrat Bahu, Manado',
                'website' => 'https://www.unsrat.ac.id',
                'email' => 'ellen.kumaat@unsrat.ac.id',
                'telepon' => '0431-851234',
                'logo' => 'unsrat-logo.jpg',
                'tanggal_mou' => '2024-01-01',
                'tanggal_berakhir' => '2027-01-01',
                'status' => 'aktif',
                'urutan' => 17,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Institut Teknologi Bandung',
                'deskripsi' => 'Kerjasama dalam penelitian teknologi dan pertukaran mahasiswa.',
                'kategori' => 'Universitas',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Ganesha No.10, Bandung',
                'website' => 'https://www.itb.ac.id',
                'email' => 'humas@itb.ac.id',
                'telepon' => '022-2500000',
                'logo' => 'itb-logo.jpg',
                'tanggal_mou' => '2024-02-01',
                'tanggal_berakhir' => '2027-02-01',
                'status' => 'aktif',
                'urutan' => 18,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Universitas Gadjah Mada',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi dan inovasi.',
                'kategori' => 'Universitas',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Bulaksumur, Yogyakarta',
                'website' => 'https://www.ugm.ac.id',
                'email' => 'humas@ugm.ac.id',
                'telepon' => '0274-588688',
                'logo' => 'ugm-logo.jpg',
                'tanggal_mou' => '2024-03-01',
                'tanggal_berakhir' => '2027-03-01',
                'status' => 'aktif',
                'urutan' => 19,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Universitas Indonesia',
                'deskripsi' => 'Kerjasama dalam penelitian multidisiplin dan pengembangan SDM.',
                'kategori' => 'Universitas',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Salemba Raya No.4, Jakarta Pusat',
                'website' => 'https://www.ui.ac.id',
                'email' => 'humas@ui.ac.id',
                'telepon' => '021-7867222',
                'logo' => 'ui-logo.jpg',
                'tanggal_mou' => '2024-04-01',
                'tanggal_berakhir' => '2027-04-01',
                'status' => 'aktif',
                'urutan' => 20,
                'is_active' => true,
            ],

            // Pemerintah
            [
                'nama_instansi' => 'Dinas Pekerjaan Umum Provinsi Sulawesi Utara',
                'deskripsi' => 'Kerjasama dalam pengabdian masyarakat dan konsultasi infrastruktur.',
                'kategori' => 'Pemerintah',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Pengabdian Masyarakat',
                'alamat' => 'Jl. 17 Agustus No.69, Manado',
                'website' => 'https://pupr.sulutprov.go.id',
                'email' => 'markus.tumundo@sulutprov.go.id',
                'telepon' => '0431-851234',
                'logo' => 'pu-sulut-logo.jpg',
                'tanggal_mou' => '2023-12-01',
                'tanggal_berakhir' => '2025-12-01',
                'status' => 'aktif',
                'urutan' => 21,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Dinas Perhubungan Provinsi Sulawesi Utara',
                'deskripsi' => 'Kerjasama dalam pengembangan sistem transportasi dan infrastruktur jalan.',
                'kategori' => 'Pemerintah',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. 17 Agustus No.70, Manado',
                'website' => 'https://dishub.sulutprov.go.id',
                'email' => 'dishub@sulutprov.go.id',
                'telepon' => '0431-851235',
                'logo' => 'dishub-sulut-logo.jpg',
                'tanggal_mou' => '2024-05-01',
                'tanggal_berakhir' => '2027-05-01',
                'status' => 'aktif',
                'urutan' => 22,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Dinas Lingkungan Hidup Provinsi Sulawesi Utara',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi ramah lingkungan.',
                'kategori' => 'Pemerintah',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. 17 Agustus No.71, Manado',
                'website' => 'https://dlh.sulutprov.go.id',
                'email' => 'dlh@sulutprov.go.id',
                'telepon' => '0431-851236',
                'logo' => 'dlh-sulut-logo.jpg',
                'tanggal_mou' => '2024-06-01',
                'tanggal_berakhir' => '2027-06-01',
                'status' => 'aktif',
                'urutan' => 23,
                'is_active' => true,
            ],

            // Lembaga Penelitian
            [
                'nama_instansi' => 'Lembaga Ilmu Pengetahuan Indonesia (LIPI)',
                'deskripsi' => 'Kerjasama dalam penelitian teknologi dan inovasi.',
                'kategori' => 'Lembaga Penelitian',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Gatot Subroto No.10, Jakarta Selatan',
                'website' => 'https://www.lipi.go.id',
                'email' => 'humas@lipi.go.id',
                'telepon' => '021-5225711',
                'logo' => 'lipi-logo.jpg',
                'tanggal_mou' => '2024-07-01',
                'tanggal_berakhir' => '2027-07-01',
                'status' => 'aktif',
                'urutan' => 24,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'Badan Pengkajian dan Penerapan Teknologi (BPPT)',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi terapan.',
                'kategori' => 'Lembaga Penelitian',
                'jurusan' => 'Semua Jurusan',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. M.H. Thamrin No.8, Jakarta Pusat',
                'website' => 'https://www.bppt.go.id',
                'email' => 'humas@bppt.go.id',
                'telepon' => '021-3169770',
                'logo' => 'bppt-logo.jpg',
                'tanggal_mou' => '2024-08-01',
                'tanggal_berakhir' => '2027-08-01',
                'status' => 'aktif',
                'urutan' => 25,
                'is_active' => true,
            ],

            // Perusahaan Tambahan
            [
                'nama_instansi' => 'PT Freeport Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi pertambangan.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Sudirman Kav. 52-53, Jakarta Pusat',
                'website' => 'https://www.ptfi.co.id',
                'email' => 'info@ptfi.co.id',
                'telepon' => '021-5268888',
                'logo' => 'freeport-logo.jpg',
                'tanggal_mou' => '2024-09-01',
                'tanggal_berakhir' => '2027-09-01',
                'status' => 'aktif',
                'urutan' => 26,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Bukit Asam Tbk',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi energi batubara.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Mesin',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Parigi No.1, Tanjung Enim, Sumatera Selatan',
                'website' => 'https://www.bukitasam.co.id',
                'email' => 'info@bukitasam.co.id',
                'telepon' => '0734-451096',
                'logo' => 'bukit-asam-logo.jpg',
                'tanggal_mou' => '2024-10-01',
                'tanggal_berakhir' => '2027-10-01',
                'status' => 'aktif',
                'urutan' => 27,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Semen Indonesia Tbk',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi material konstruksi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Veteran Gresik, Jawa Timur',
                'website' => 'https://www.semenindonesia.com',
                'email' => 'info@semenindonesia.com',
                'telepon' => '031-3981818',
                'logo' => 'semen-indonesia-logo.jpg',
                'tanggal_mou' => '2024-11-01',
                'tanggal_berakhir' => '2027-11-01',
                'status' => 'aktif',
                'urutan' => 28,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Holcim Indonesia Tbk',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi beton dan material.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Sipil',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 38, Jakarta Selatan',
                'website' => 'https://www.holcim.co.id',
                'email' => 'info@holcim.co.id',
                'telepon' => '021-5200000',
                'logo' => 'holcim-logo.jpg',
                'tanggal_mou' => '2024-12-01',
                'tanggal_berakhir' => '2027-12-01',
                'status' => 'aktif',
                'urutan' => 29,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Schneider Electric Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi elektrikal dan otomasi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Elektro',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.se.com/id',
                'email' => 'info@se.com',
                'telepon' => '021-5200000',
                'logo' => 'schneider-logo.jpg',
                'tanggal_mou' => '2025-01-01',
                'tanggal_berakhir' => '2028-01-01',
                'status' => 'aktif',
                'urutan' => 30,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Siemens Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi industri dan otomasi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Elektro',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.siemens.com/id',
                'email' => 'info@siemens.com',
                'telepon' => '021-5200000',
                'logo' => 'siemens-logo.jpg',
                'tanggal_mou' => '2025-02-01',
                'tanggal_berakhir' => '2028-02-01',
                'status' => 'aktif',
                'urutan' => 31,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT ABB Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi power dan otomasi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Elektro',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.abb.com/id',
                'email' => 'info@abb.com',
                'telepon' => '021-5200000',
                'logo' => 'abb-logo.jpg',
                'tanggal_mou' => '2025-03-01',
                'tanggal_berakhir' => '2028-03-01',
                'status' => 'aktif',
                'urutan' => 32,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Samsung Electronics Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi mobile dan IoT.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.samsung.com/id',
                'email' => 'info@samsung.com',
                'telepon' => '021-5200000',
                'logo' => 'samsung-logo.jpg',
                'tanggal_mou' => '2025-04-01',
                'tanggal_berakhir' => '2028-04-01',
                'status' => 'aktif',
                'urutan' => 33,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Apple Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan aplikasi iOS dan teknologi mobile.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.apple.com/id',
                'email' => 'info@apple.com',
                'telepon' => '021-5200000',
                'logo' => 'apple-logo.jpg',
                'tanggal_mou' => '2025-05-01',
                'tanggal_berakhir' => '2028-05-01',
                'status' => 'aktif',
                'urutan' => 34,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Facebook Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi sosial media dan AI.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.facebook.com',
                'email' => 'info@facebook.com',
                'telepon' => '021-5200000',
                'logo' => 'facebook-logo.jpg',
                'tanggal_mou' => '2025-06-01',
                'tanggal_berakhir' => '2028-06-01',
                'status' => 'aktif',
                'urutan' => 35,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Amazon Web Services Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi cloud computing.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://aws.amazon.com/id',
                'email' => 'info@aws.com',
                'telepon' => '021-5200000',
                'logo' => 'aws-logo.jpg',
                'tanggal_mou' => '2025-07-01',
                'tanggal_berakhir' => '2028-07-01',
                'status' => 'aktif',
                'urutan' => 36,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Alibaba Cloud Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi e-commerce dan cloud.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.alibabacloud.com',
                'email' => 'info@alibabacloud.com',
                'telepon' => '021-5200000',
                'logo' => 'alibaba-logo.jpg',
                'tanggal_mou' => '2025-08-01',
                'tanggal_berakhir' => '2028-08-01',
                'status' => 'aktif',
                'urutan' => 37,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Grab Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi transportasi dan fintech.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian Bersama',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.grab.com/id',
                'email' => 'info@grab.com',
                'telepon' => '021-5200000',
                'logo' => 'grab-logo.jpg',
                'tanggal_mou' => '2025-09-01',
                'tanggal_berakhir' => '2028-09-01',
                'status' => 'aktif',
                'urutan' => 38,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT GoTo Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi e-commerce dan transportasi.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Praktik Kerja Lapangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.gojek.com',
                'email' => 'info@gojek.com',
                'telepon' => '021-5200000',
                'logo' => 'goto-logo.jpg',
                'tanggal_mou' => '2025-10-01',
                'tanggal_berakhir' => '2028-10-01',
                'status' => 'aktif',
                'urutan' => 39,
                'is_active' => true,
            ],
            [
                'nama_instansi' => 'PT Tokopedia Indonesia',
                'deskripsi' => 'Kerjasama dalam pengembangan teknologi e-commerce dan marketplace.',
                'kategori' => 'Perusahaan',
                'jurusan' => 'Teknik Informatika',
                'bentuk_kerjasama' => 'Penelitian dan Pengembangan',
                'alamat' => 'Jl. Jend. Gatot Subroto Kav. 18, Jakarta Selatan',
                'website' => 'https://www.tokopedia.com',
                'email' => 'info@tokopedia.com',
                'telepon' => '021-5200000',
                'logo' => 'tokopedia-logo.jpg',
                'tanggal_mou' => '2025-11-01',
                'tanggal_berakhir' => '2028-11-01',
                'status' => 'aktif',
                'urutan' => 40,
                'is_active' => true,
            ],
        ];

        foreach ($mitras as $mitra) {
            MitraKerjasama::firstOrCreate(
                ['nama_instansi' => $mitra['nama_instansi']],
                $mitra
            );
        }
    }
}
