<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Ormawa;

class OrmawaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ormawas = [
            [
                'jenis' => 'bem',
                'nama' => 'Badan Eksekutif Mahasiswa Fakultas Teknik',
                'singkatan' => 'BEM Fatek',
                'deskripsi' => 'Organisasi tertinggi mahasiswa yang mengkoordinasikan seluruh kegiatan kemahasiswaan di tingkat fakultas. BEM Fatek berperan sebagai wadah aspirasi mahasiswa dan mitra kerja pimpinan fakultas dalam pengembangan kemahasiswaan.',
                'ketua' => 'Ahmad Fadillah',
                'email' => 'bem@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 123',
                'lokasi' => 'Ruang BEM Lt. 1, Gedung Fakultas Teknik',
                'website' => 'https://bem-fatek.unima.ac.id',
                'instagram' => '@bemfatek_unima',
                'facebook' => 'BEM Fatek UNIMA',
                'youtube' => 'BEM Fatek UNIMA Official',
                'warna' => 'blue',
                'icon' => 'fas fa-users',
                'urutan' => 1,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Lomba Paduan Suara Antar Fakultas' => '2024',
                    'Best Community Service Award' => '2023',
                    'Juara 2 Futsal Antar Fakultas' => '2023',
                ],
                'program_unggulan' => [
                    'Fatek Mengajar' => 'Program pengabdian ke sekolah-sekolah',
                    'Startup Competition' => 'Kompetisi startup mahasiswa',
                    'Fatek Peduli' => 'Program sosial kemasyarakatan',
                ],
                'catatan' => 'BEM Fatek merupakan organisasi tertinggi mahasiswa di tingkat fakultas.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Informatika',
                'singkatan' => 'HMTI',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Informatika yang fokus pada pengembangan akademik dan profesional di bidang teknologi informasi dan komputer.',
                'ketua' => 'Sarah Putri',
                'email' => 'hmti@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 124',
                'lokasi' => 'Ruang HMTI Lt. 2, Gedung Fatek',
                'website' => 'https://hmti.unima.ac.id',
                'instagram' => '@hmti_unima',
                'facebook' => 'HMTI UNIMA',
                'youtube' => 'HMTI UNIMA Official',
                'warna' => 'green',
                'icon' => 'fas fa-graduation-cap',
                'urutan' => 2,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Robotik Nasional' => '2024',
                    'Juara 2 Programming Competition' => '2024',
                    'Best Paper di Konferensi Nasional' => '2023',
                ],
                'program_unggulan' => [
                    'Coding Bootcamp' => 'Pelatihan programming intensif',
                    'Tech Talk Series' => 'Seminar teknologi terkini',
                    'Hackathon Fatek' => 'Kompetisi coding 24 jam',
                ],
                'catatan' => 'HMTI merupakan himpunan jurusan dengan prestasi akademik tertinggi.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Sipil',
                'singkatan' => 'HMTS',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Sipil yang berfokus pada pengembangan keahlian di bidang konstruksi, infrastruktur, dan teknik sipil.',
                'ketua' => 'Budi Santoso',
                'email' => 'hmts@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 125',
                'lokasi' => 'Ruang HMTS Lt. 2, Gedung Fatek',
                'website' => 'https://hmts.unima.ac.id',
                'instagram' => '@hmts_unima',
                'facebook' => 'HMTS UNIMA',
                'youtube' => 'HMTS UNIMA Official',
                'warna' => 'orange',
                'icon' => 'fas fa-building',
                'urutan' => 3,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Bridge Design' => '2024',
                    'Juara 2 Concrete Competition' => '2023',
                    'Best Design Award' => '2023',
                ],
                'program_unggulan' => [
                    'Bridge Building Competition' => 'Kompetisi desain jembatan',
                    'Construction Workshop' => 'Workshop konstruksi',
                    'Infrastructure Study Tour' => 'Kunjungan proyek infrastruktur',
                ],
                'catatan' => 'HMTS aktif dalam kompetisi desain dan konstruksi.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Elektro',
                'singkatan' => 'HMTE',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Elektro yang fokus pada pengembangan keahlian di bidang elektro, elektronika, dan sistem kontrol.',
                'ketua' => 'Dewi Sartika',
                'email' => 'hmte@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 126',
                'lokasi' => 'Ruang HMTE Lt. 2, Gedung Fatek',
                'website' => 'https://hmte.unima.ac.id',
                'instagram' => '@hmte_unima',
                'facebook' => 'HMTE UNIMA',
                'youtube' => 'HMTE UNIMA Official',
                'warna' => 'yellow',
                'icon' => 'fas fa-bolt',
                'urutan' => 4,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Robot Line Follower' => '2024',
                    'Juara 2 Electrical Design Competition' => '2023',
                    'Best Innovation Award' => '2023',
                ],
                'program_unggulan' => [
                    'Electronics Workshop' => 'Workshop elektronika',
                    'Smart Home Project' => 'Proyek rumah pintar',
                    'Renewable Energy Seminar' => 'Seminar energi terbarukan',
                ],
                'catatan' => 'HMTE unggul dalam kompetisi robotik dan elektronika.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Mesin',
                'singkatan' => 'HMTM',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Mesin yang berfokus pada pengembangan keahlian di bidang mesin, manufaktur, dan otomasi industri.',
                'ketua' => 'Rizki Pratama',
                'email' => 'hmtm@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 127',
                'lokasi' => 'Ruang HMTM Lt. 2, Gedung Fatek',
                'website' => 'https://hmtm.unima.ac.id',
                'instagram' => '@hmtm_unima',
                'facebook' => 'HMTM UNIMA',
                'youtube' => 'HMTM UNIMA Official',
                'warna' => 'red',
                'icon' => 'fas fa-cogs',
                'urutan' => 5,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi CAD Design' => '2024',
                    'Juara 2 Manufacturing Competition' => '2023',
                    'Best Engineering Award' => '2023',
                ],
                'program_unggulan' => [
                    'CAD Workshop' => 'Workshop desain CAD',
                    'Manufacturing Expo' => 'Pameran manufaktur',
                    'Industry Visit' => 'Kunjungan industri',
                ],
                'catatan' => 'HMTM aktif dalam pengembangan teknologi manufaktur.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Arsitektur',
                'singkatan' => 'HMA',
                'deskripsi' => 'Himpunan mahasiswa jurusan Arsitektur yang fokus pada pengembangan kreativitas dan keahlian di bidang arsitektur dan desain.',
                'ketua' => 'Nina Kartika',
                'email' => 'hma@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 128',
                'lokasi' => 'Ruang HMA Lt. 2, Gedung Fatek',
                'website' => 'https://hma.unima.ac.id',
                'instagram' => '@hma_unima',
                'facebook' => 'HMA UNIMA',
                'youtube' => 'HMA UNIMA Official',
                'warna' => 'purple',
                'icon' => 'fas fa-drafting-compass',
                'urutan' => 6,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Architectural Design Competition' => '2024',
                    'Juara 2 Sustainable Design Award' => '2023',
                    'Best Creative Award' => '2023',
                ],
                'program_unggulan' => [
                    'Design Studio Workshop' => 'Workshop studio desain',
                    'Architecture Exhibition' => 'Pameran arsitektur',
                    'Heritage Conservation Project' => 'Proyek konservasi heritage',
                ],
                'catatan' => 'HMA unggul dalam kompetisi desain arsitektur.',
            ],
            [
                'jenis' => 'ukm',
                'nama' => 'Unit Kegiatan Mahasiswa Seni & Budaya',
                'singkatan' => 'UKM Seni',
                'deskripsi' => 'Unit kegiatan mahasiswa yang menampung dan mengembangkan bakat mahasiswa dalam bidang seni dan budaya, termasuk musik, tari, teater, dan seni rupa.',
                'ketua' => 'Maya Indah',
                'email' => 'ukmseni@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 129',
                'lokasi' => 'Ruang Seni Lt. 1, Gedung Fatek',
                'website' => null,
                'instagram' => '@ukmseni_fatek',
                'facebook' => 'UKM Seni Fatek UNIMA',
                'youtube' => 'UKM Seni Fatek UNIMA',
                'warna' => 'teal',
                'icon' => 'fas fa-music',
                'urutan' => 7,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Lomba Paduan Suara' => '2024',
                    'Juara 2 Festival Tari Tradisional' => '2023',
                    'Best Performance Award' => '2023',
                ],
                'program_unggulan' => [
                    'Pentas Seni Tahunan' => 'Pentas seni tahunan mahasiswa',
                    'Workshop Seni' => 'Workshop seni dan budaya',
                    'Cultural Performance' => 'Pertunjukan budaya',
                ],
                'catatan' => 'UKM Seni aktif dalam berbagai festival seni dan budaya.',
            ],
            [
                'jenis' => 'ukm',
                'nama' => 'Unit Kegiatan Mahasiswa Olahraga',
                'singkatan' => 'UKM Olahraga',
                'deskripsi' => 'Unit kegiatan mahasiswa yang mengembangkan bakat dan minat mahasiswa dalam berbagai cabang olahraga, termasuk futsal, basket, voli, dan atletik.',
                'ketua' => 'Andi Wijaya',
                'email' => 'ukmolahraga@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 130',
                'lokasi' => 'Lapangan Olahraga, Kampus Fatek',
                'website' => null,
                'instagram' => '@ukmolahraga_fatek',
                'facebook' => 'UKM Olahraga Fatek UNIMA',
                'youtube' => 'UKM Olahraga Fatek UNIMA',
                'warna' => 'indigo',
                'icon' => 'fas fa-futbol',
                'urutan' => 8,
                'is_active' => true,
                'prestasi' => [
                    'Juara 2 Futsal Antar Fakultas' => '2024',
                    'Juara 1 Basket Putra' => '2023',
                    'Juara 3 Voli Putri' => '2023',
                ],
                'program_unggulan' => [
                    'Turnamen Olahraga' => 'Turnamen olahraga antar jurusan',
                    'Fitness Center' => 'Pusat kebugaran mahasiswa',
                    'Sports Clinic' => 'Klinik olahraga',
                ],
                'catatan' => 'UKM Olahraga aktif dalam berbagai kompetisi olahraga.',
            ],
        ];

        foreach ($ormawas as $ormawa) {
            Ormawa::create($ormawa);
        }
    }
}
