<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ormawa;

class OrmawaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ormawas = [
            // ==== DATA LAMA (8 entri) ====
            [
                'jenis' => 'bem',
                'nama' => 'Badan Eksekutif Mahasiswa Fakultas Teknik',
                'singkatan' => 'BEM Fatek',
                'deskripsi' => 'Organisasi tertinggi mahasiswa yang mengkoordinasikan seluruh kegiatan kemahasiswaan di tingkat fakultas. BEM Fatek berperan sebagai wadah aspirasi mahasiswa dan mitra kerja pimpinan fakultas dalam pengembangan kemahasiswaan.',
                'ketua' => 'Ahmad Fadillah',
                'email' => 'bem@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 123',
                'lokasi' => 'Ruang BEM Lt. 1, Gedung Fakultas Teknik',
                'website' => 'https://bem-fatek.unima.ac.id',
                'instagram' => '@bemfatek_unima',
                'facebook' => 'BEM Fatek UNIMA',
                'youtube' => 'BEM Fatek UNIMA Official',
                'warna' => 'blue',
                'icon' => 'fas fa-users',
                'urutan' => 1,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Lomba Paduan Suara Antar Fakultas' => '2024',
                    'Best Community Service Award' => '2023',
                    'Juara 2 Futsal Antar Fakultas' => '2023',
                ],
                'program_unggulan' => [
                    'Fatek Mengajar' => 'Program pengabdian ke sekolah-sekolah',
                    'Startup Competition' => 'Kompetisi startup mahasiswa',
                    'Fatek Peduli' => 'Program sosial kemasyarakatan',
                ],
                'catatan' => 'BEM Fatek merupakan organisasi tertinggi mahasiswa di tingkat fakultas.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Informatika',
                'singkatan' => 'HMTI',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Informatika yang fokus pada pengembangan akademik dan profesional di bidang teknologi informasi dan komputer.',
                'ketua' => 'Sarah Putri',
                'email' => 'hmti@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 124',
                'lokasi' => 'Ruang HMTI Lt. 2, Gedung Fatek',
                'website' => 'https://hmti.unima.ac.id',
                'instagram' => '@hmti_unima',
                'facebook' => 'HMTI UNIMA',
                'youtube' => 'HMTI UNIMA Official',
                'warna' => 'green',
                'icon' => 'fas fa-graduation-cap',
                'urutan' => 2,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Robotik Nasional' => '2024',
                    'Juara 2 Programming Competition' => '2024',
                    'Best Paper di Konferensi Nasional' => '2023',
                ],
                'program_unggulan' => [
                    'Coding Bootcamp' => 'Pelatihan programming intensif',
                    'Tech Talk Series' => 'Seminar teknologi terkini',
                    'Hackathon Fatek' => 'Kompetisi coding 24 jam',
                ],
                'catatan' => 'HMTI merupakan himpunan jurusan dengan prestasi akademik tertinggi.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Sipil',
                'singkatan' => 'HMTS',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Sipil yang berfokus pada pengembangan keahlian di bidang konstruksi, infrastruktur, dan teknik sipil.',
                'ketua' => 'Budi Santoso',
                'email' => 'hmts@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 125',
                'lokasi' => 'Ruang HMTS Lt. 2, Gedung Fatek',
                'website' => 'https://hmts.unima.ac.id',
                'instagram' => '@hmts_unima',
                'facebook' => 'HMTS UNIMA',
                'youtube' => 'HMTS UNIMA Official',
                'warna' => 'orange',
                'icon' => 'fas fa-building',
                'urutan' => 3,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Bridge Design' => '2024',
                    'Juara 2 Concrete Competition' => '2023',
                    'Best Design Award' => '2023',
                ],
                'program_unggulan' => [
                    'Bridge Building Competition' => 'Kompetisi desain jembatan',
                    'Construction Workshop' => 'Workshop konstruksi',
                    'Infrastructure Study Tour' => 'Kunjungan proyek infrastruktur',
                ],
                'catatan' => 'HMTS aktif dalam kompetisi desain dan konstruksi.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Elektro',
                'singkatan' => 'HMTE',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Elektro yang fokus pada pengembangan keahlian di bidang elektro, elektronika, dan sistem kontrol.',
                'ketua' => 'Dewi Sartika',
                'email' => 'hmte@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 126',
                'lokasi' => 'Ruang HMTE Lt. 2, Gedung Fatek',
                'website' => 'https://hmte.unima.ac.id',
                'instagram' => '@hmte_unima',
                'facebook' => 'HMTE UNIMA',
                'youtube' => 'HMTE UNIMA Official',
                'warna' => 'yellow',
                'icon' => 'fas fa-bolt',
                'urutan' => 4,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi Robot Line Follower' => '2024',
                    'Juara 2 Electrical Design Competition' => '2023',
                    'Best Innovation Award' => '2023',
                ],
                'program_unggulan' => [
                    'Electronics Workshop' => 'Workshop elektronika',
                    'Smart Home Project' => 'Proyek rumah pintar',
                    'Renewable Energy Seminar' => 'Seminar energi terbarukan',
                ],
                'catatan' => 'HMTE unggul dalam kompetisi robotik dan elektronika.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Mesin',
                'singkatan' => 'HMTM',
                'deskripsi' => 'Himpunan mahasiswa jurusan Teknik Mesin yang berfokus pada pengembangan keahlian di bidang mesin, manufaktur, dan otomasi industri.',
                'ketua' => 'Rizki Pratama',
                'email' => 'hmtm@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 127',
                'lokasi' => 'Ruang HMTM Lt. 2, Gedung Fatek',
                'website' => 'https://hmtm.unima.ac.id',
                'instagram' => '@hmtm_unima',
                'facebook' => 'HMTM UNIMA',
                'youtube' => 'HMTM UNIMA Official',
                'warna' => 'red',
                'icon' => 'fas fa-cogs',
                'urutan' => 5,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Kompetisi CAD Design' => '2024',
                    'Juara 2 Manufacturing Competition' => '2023',
                    'Best Engineering Award' => '2023',
                ],
                'program_unggulan' => [
                    'CAD Workshop' => 'Workshop desain CAD',
                    'Manufacturing Expo' => 'Pameran manufaktur',
                    'Industry Visit' => 'Kunjungan industri',
                ],
                'catatan' => 'HMTM aktif dalam pengembangan teknologi manufaktur.',
            ],
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Arsitektur',
                'singkatan' => 'HMA',
                'deskripsi' => 'Himpunan mahasiswa jurusan Arsitektur yang fokus pada pengembangan kreativitas dan keahlian di bidang arsitektur dan desain.',
                'ketua' => 'Nina Kartika',
                'email' => 'hma@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 128',
                'lokasi' => 'Ruang HMA Lt. 2, Gedung Fatek',
                'website' => 'https://hma.unima.ac.id',
                'instagram' => '@hma_unima',
                'facebook' => 'HMA UNIMA',
                'youtube' => 'HMA UNIMA Official',
                'warna' => 'purple',
                'icon' => 'fas fa-drafting-compass',
                'urutan' => 6,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Architectural Design Competition' => '2024',
                    'Juara 2 Sustainable Design Award' => '2023',
                    'Best Creative Award' => '2023',
                ],
                'program_unggulan' => [
                    'Design Studio Workshop' => 'Workshop studio desain',
                    'Architecture Exhibition' => 'Pameran arsitektur',
                    'Heritage Conservation Project' => 'Proyek konservasi heritage',
                ],
                'catatan' => 'HMA unggul dalam kompetisi desain arsitektur.',
            ],
            [
                'jenis' => 'ukm',
                'nama' => 'Unit Kegiatan Mahasiswa Seni & Budaya',
                'singkatan' => 'UKM Seni',
                'deskripsi' => 'Unit kegiatan mahasiswa yang menampung dan mengembangkan bakat mahasiswa dalam bidang seni dan budaya, termasuk musik, tari, teater, dan seni rupa.',
                'ketua' => 'Maya Indah',
                'email' => 'ukmseni@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 129',
                'lokasi' => 'Ruang Seni Lt. 1, Gedung Fatek',
                'website' => null,
                'instagram' => '@ukmseni_fatek',
                'facebook' => 'UKM Seni Fatek UNIMA',
                'youtube' => 'UKM Seni Fatek UNIMA',
                'warna' => 'teal',
                'icon' => 'fas fa-music',
                'urutan' => 7,
                'is_active' => true,
                'prestasi' => [
                    'Juara 1 Lomba Paduan Suara' => '2024',
                    'Juara 2 Festival Tari Tradisional' => '2023',
                    'Best Performance Award' => '2023',
                ],
                'program_unggulan' => [
                    'Pentas Seni Tahunan' => 'Pentas seni tahunan mahasiswa',
                    'Workshop Seni' => 'Workshop seni dan budaya',
                    'Cultural Performance' => 'Pertunjukan budaya',
                ],
                'catatan' => 'UKM Seni aktif dalam berbagai festival seni dan budaya.',
            ],
            [
                'jenis' => 'ukm',
                'nama' => 'Unit Kegiatan Mahasiswa Olahraga',
                'singkatan' => 'UKM Olahraga',
                'deskripsi' => 'Unit kegiatan mahasiswa yang mengembangkan bakat dan minat mahasiswa dalam berbagai cabang olahraga, termasuk futsal, basket, voli, dan atletik.',
                'ketua' => 'Andi Wijaya',
                'email' => 'ukmolahraga@fatek.unima.ac.id',
                'telepon' => '+62-431-123456 ext. 130',
                'lokasi' => 'Lapangan Olahraga, Kampus Fatek',
                'website' => null,
                'instagram' => '@ukmolahraga_fatek',
                'facebook' => 'UKM Olahraga Fatek UNIMA',
                'youtube' => 'UKM Olahraga Fatek UNIMA',
                'warna' => 'indigo',
                'icon' => 'fas fa-futbol',
                'urutan' => 8,
                'is_active' => true,
                'prestasi' => [
                    'Juara 2 Futsal Antar Fakultas' => '2024',
                    'Juara 1 Basket Putra' => '2023',
                    'Juara 3 Voli Putri' => '2023',
                ],
                'program_unggulan' => [
                    'Turnamen Olahraga' => 'Turnamen olahraga antar jurusan',
                    'Fitness Center' => 'Pusat kebugaran mahasiswa',
                    'Sports Clinic' => 'Klinik olahraga',
                ],
                'catatan' => 'UKM Olahraga aktif dalam berbagai kompetisi olahraga.',
            ],

            // ==== TAMBAHAN 17 ENTRI SESUAI DAFTAR KAMU ====
            // 1) KPRM
            [
                'jenis' => 'kprm',
                'nama' => 'Komisi Pemilihan Raya Mahasiswa FT UNIMA',
                'singkatan' => 'KPRM FT',
                'deskripsi' => 'Penyelenggara pemilihan raya mahasiswa tingkat fakultas.',
                'ketua' => 'Henriko',
                'email' => null,
                'telepon' => '+62 851-8299-8604, +62 823-9741-6247',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'orange',
                'icon' => 'fas fa-vote-yea',
                'urutan' => 9,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Inri (+62 823-9741-6247)',
            ],
            // 2) DPM
            [
                'jenis' => 'dpm',
                'nama' => 'Dewan Perwakilan Mahasiswa FT UNIMA',
                'singkatan' => 'DPM FT',
                'deskripsi' => 'Lembaga legislatif mahasiswa tingkat fakultas.',
                'ketua' => 'Anisa',
                'email' => null,
                'telepon' => '+62 821-9678-6702, +62 882-1237-6055',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'indigo',
                'icon' => 'fas fa-gavel',
                'urutan' => 10,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Oswald (+62 882-1237-6055)',
            ],
            // 3) (BEM sudah ada di atas)

            // 4) UPK-MK (kerohanian) -> UKM
            [
                'jenis' => 'ukm',
                'nama' => 'Unit Pelayanan Kerohanian - Mahasiswa Kristen FT UNIMA',
                'singkatan' => 'UPK-MK FT',
                'deskripsi' => 'Pelayanan kerohanian mahasiswa Kristen tingkat Fakultas Teknik.',
                'ketua' => 'Jarman',
                'email' => null,
                'telepon' => '+62 822-8696-2129, +62 856-9641-1403',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'green',
                'icon' => 'fas fa-hands-praying',
                'urutan' => 11,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Sidney (+62 856-9641-1403)',
            ],
            // 5) BTM (kerohanian) -> UKM
            [
                'jenis' => 'ukm',
                'nama' => 'Badan Tadzkir Mahasiswa FT UNIMA',
                'singkatan' => 'BTM FT',
                'deskripsi' => 'Pelayanan kerohanian mahasiswa Muslim tingkat Fakultas Teknik.',
                'ketua' => 'Grenly',
                'email' => null,
                'telepon' => '+62 812-4870-0788, +62 856-9641-1403',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'teal',
                'icon' => 'fas fa-mosque',
                'urutan' => 12,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Alfito (+62 856-9641-1403)',
            ],
            // 6) KMK -> UKM
            [
                'jenis' => 'ukm',
                'nama' => 'Keluarga Mahasiswa Katolik FT UNIMA',
                'singkatan' => 'KMK FT',
                'deskripsi' => 'Komunitas mahasiswa Katolik Fakultas Teknik.',
                'ketua' => 'Viko',
                'email' => null,
                'telepon' => '+62 813-4249-4705',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'yellow',
                'icon' => 'fas fa-church',
                'urutan' => 13,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => null,
            ],
            // 7) SSB Manguni -> UKM
            [
                'jenis' => 'ukm',
                'nama' => 'Sanggar Seni Budaya Manguni FT UNIMA',
                'singkatan' => 'SSB Manguni',
                'deskripsi' => 'Unit seni & budaya Fakultas Teknik.',
                'ketua' => 'Aldy',
                'email' => null,
                'telepon' => '+62 895-3324-63131, +62 895-3050-6014',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'purple',
                'icon' => 'fas fa-theater-masks',
                'urutan' => 14,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Fito (+62 895-3050-6014)',
            ],
            // 8) Mapala Technology -> UKM
            [
                'jenis' => 'ukm',
                'nama' => 'Mahasiswa Pencinta Alam Technology FT UNIMA',
                'singkatan' => 'Mapala Technology',
                'deskripsi' => 'Unit kegiatan pecinta alam Fakultas Teknik.',
                'ketua' => 'Febrianti',
                'email' => null,
                'telepon' => '+62 856-9669-3007, +62 856-9641-1403',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'green',
                'icon' => 'fas fa-mountain',
                'urutan' => 15,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Sindy (+62 856-9641-1403)',
            ],
            // 9) HMJ PTB -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Jurusan Pendidikan Teknik Bangunan FT UNIMA',
                'singkatan' => 'HMJ PTB',
                'deskripsi' => 'Himpunan mahasiswa jurusan Pendidikan Teknik Bangunan.',
                'ketua' => 'Aldi',
                'email' => null,
                'telepon' => '+62 895-3324-63131',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'orange',
                'icon' => 'fas fa-tools',
                'urutan' => 16,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'PJ: Aldi',
            ],
            // 10) HMJ PTE -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Jurusan Pendidikan Teknik Elektro FT UNIMA',
                'singkatan' => 'HMJ PTE',
                'deskripsi' => 'Himpunan mahasiswa jurusan Pendidikan Teknik Elektro.',
                'ketua' => 'Egi',
                'email' => null,
                'telepon' => '+62 831-6699-5976, +62 895-6130-70403',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'yellow',
                'icon' => 'fas fa-bolt',
                'urutan' => 17,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Juventus (+62 895-6130-70403)',
            ],
            // 11) HMJ PKK -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Jurusan Pendidikan Kesejahteraan Keluarga FT UNIMA',
                'singkatan' => 'HMJ PKK',
                'deskripsi' => 'Himpunan mahasiswa jurusan Pendidikan Kesejahteraan Keluarga.',
                'ketua' => 'Victoria',
                'email' => null,
                'telepon' => '+62 823-9767-4476, +62 822-1709-5595',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'pink',
                'icon' => 'fas fa-utensils',
                'urutan' => 18,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Gita (+62 822-1709-5595)',
            ],
            // 12) HMJ PTM (Pendidikan Teknik Mesin) -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Jurusan Pendidikan Teknik Mesin FT UNIMA',
                'singkatan' => 'HMJ PTM',
                'deskripsi' => 'Himpunan mahasiswa jurusan Pendidikan Teknik Mesin.',
                'ketua' => 'Richard',
                'email' => null,
                'telepon' => '+62 856-9625-9052, +62 812-4366-0630',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'red',
                'icon' => 'fas fa-cogs',
                'urutan' => 19,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Maikel (+62 812-4366-0630)',
            ],
            // 13) HMJ PTIK -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Jurusan Pendidikan Teknologi Informasi dan Komunikasi FT UNIMA',
                'singkatan' => 'HMJ PTIK',
                'deskripsi' => 'Himpunan mahasiswa jurusan PTIK.',
                'ketua' => 'Brandon',
                'email' => null,
                'telepon' => '+62 899-1651-166, +62 853-4384-4716',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'green',
                'icon' => 'fas fa-laptop-code',
                'urutan' => 20,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Rei (+62 853-4384-4716)',
            ],
            // 14) HIMA ARS -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Arsitektur FT UNIMA',
                'singkatan' => 'HIMA ARS',
                'deskripsi' => 'Himpunan mahasiswa Teknik Arsitektur.',
                'ketua' => 'Rachel',
                'email' => null,
                'telepon' => '+62 821-9403-7454, +62 816-4324-565',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'purple',
                'icon' => 'fas fa-ruler-combined',
                'urutan' => 21,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Claudia (+62 816-4324-565)',
            ],
            // 15) HMTS (sudah ada di atas — dibiarkan; updateOrCreate akan update)
            // 16) HMTM (sudah ada di atas — dibiarkan; updateOrCreate akan update)

            // 17) HIMA IF (Teknik Informatika) -> Himpunan
            [
                'jenis' => 'himpunan',
                'nama' => 'Himpunan Mahasiswa Teknik Informatika FT UNIMA',
                'singkatan' => 'HIMA IF',
                'deskripsi' => 'Himpunan mahasiswa Teknik Informatika (IF).',
                'ketua' => 'Daud',
                'email' => null,
                'telepon' => '+62 853-5259-8942, +62 895-8065-82574',
                'lokasi' => null,
                'website' => null,
                'instagram' => null,
                'facebook' => null,
                'youtube' => null,
                'warna' => 'blue',
                'icon' => 'fas fa-code',
                'urutan' => 22,
                'is_active' => true,
                'prestasi' => null,
                'program_unggulan' => null,
                'catatan' => 'Sekretaris: Sweet (+62 895-8065-82574)',
            ],
        ];

        // Supaya aman di-seed berulang tanpa duplikasi.
        foreach ($ormawas as $o) {
            Ormawa::updateOrCreate(
                ['singkatan' => $o['singkatan']], // kunci unik longgar
                $o
            );
        }
    }
}