<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SurveyLayanan;

class SurveyLayananSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nama_lengkap' => 'Ahmad Rizki',
                'email' => 'ahmad.rizki@example.com',
                'telepon' => '081234567890',
                'kategori_responden' => 'mahasiswa',
                'program_studi' => 'teknik-informatika',
                'jenis_layanan' => 'akademik',
                'layanan_spesifik' => 'Pendaftaran KRS',
                'tanggal_layanan' => '2024-01-15',
                'kemudahan_akses' => 4,
                'kecepatan_pelayanan' => 4,
                'keramahan_petugas' => 5,
                'kejelasan_informasi' => 4,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 4,
                'komentar_positif' => 'Petugas sangat ramah dan informatif',
                'saran_perbaikan' => 'Bisa ditambahkan panduan online untuk pendaftaran KRS',
            ],
            [
                'nama_lengkap' => 'Sarah Putri',
                'email' => 'sarah.putri@example.com',
                'telepon' => '081234567891',
                'kategori_responden' => 'mahasiswa',
                'program_studi' => 'teknik-sipil',
                'jenis_layanan' => 'kemahasiswaan',
                'layanan_spesifik' => 'Pengurusan Beasiswa',
                'tanggal_layanan' => '2024-01-20',
                'kemudahan_akses' => 3,
                'kecepatan_pelayanan' => 3,
                'keramahan_petugas' => 4,
                'kejelasan_informasi' => 3,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 3,
                'komentar_negatif' => 'Proses pengurusan terlalu lama',
                'saran_perbaikan' => 'Perlu dipercepat proses pengurusan beasiswa',
            ],
            [
                'nama_lengkap' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'telepon' => '081234567892',
                'kategori_responden' => 'dosen',
                'unit_kerja' => 'Bagian Akademik',
                'jenis_layanan' => 'teknologi_informasi',
                'layanan_spesifik' => 'Support Sistem Informasi',
                'tanggal_layanan' => '2024-01-25',
                'kemudahan_akses' => 5,
                'kecepatan_pelayanan' => 5,
                'keramahan_petugas' => 5,
                'kejelasan_informasi' => 5,
                'kualitas_hasil' => 5,
                'kepuasan_keseluruhan' => 5,
                'komentar_positif' => 'Tim IT sangat responsif dan membantu',
                'saran_perbaikan' => 'Terus pertahankan kualitas layanan',
            ],
            [
                'nama_lengkap' => 'Dewi Sartika',
                'email' => 'dewi.sartika@example.com',
                'telepon' => '081234567893',
                'kategori_responden' => 'alumni',
                'program_studi' => 'arsitektur',
                'jenis_layanan' => 'kerjasama',
                'layanan_spesifik' => 'Program Magang Industri',
                'tanggal_layanan' => '2024-02-01',
                'kemudahan_akses' => 4,
                'kecepatan_pelayanan' => 4,
                'keramahan_petugas' => 4,
                'kejelasan_informasi' => 4,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 4,
                'komentar_positif' => 'Program magang sangat bermanfaat',
                'saran_perbaikan' => 'Tambah lebih banyak mitra industri',
            ],
            [
                'nama_lengkap' => 'Eko Prasetyo',
                'email' => 'eko.prasetyo@example.com',
                'telepon' => '081234567894',
                'kategori_responden' => 'tenaga_kependidikan',
                'unit_kerja' => 'Bagian Keuangan',
                'jenis_layanan' => 'keuangan',
                'layanan_spesifik' => 'Pengurusan Reimbursement',
                'tanggal_layanan' => '2024-02-05',
                'kemudahan_akses' => 3,
                'kecepatan_pelayanan' => 2,
                'keramahan_petugas' => 4,
                'kejelasan_informasi' => 3,
                'kualitas_hasil' => 3,
                'kepuasan_keseluruhan' => 3,
                'komentar_negatif' => 'Proses reimbursement terlalu lama',
                'saran_perbaikan' => 'Perlu disederhanakan proses pengurusan reimbursement',
            ],
            [
                'nama_lengkap' => 'Fitri Handayani',
                'email' => 'fitri.handayani@example.com',
                'telepon' => '081234567895',
                'kategori_responden' => 'mahasiswa',
                'program_studi' => 'teknik-elektro',
                'jenis_layanan' => 'sarana_prasarana',
                'layanan_spesifik' => 'Peminjaman Laboratorium',
                'tanggal_layanan' => '2024-02-10',
                'kemudahan_akses' => 4,
                'kecepatan_pelayanan' => 4,
                'keramahan_petugas' => 5,
                'kejelasan_informasi' => 4,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 4,
                'komentar_positif' => 'Laboratorium dalam kondisi baik',
                'saran_perbaikan' => 'Tambah peralatan laboratorium yang lebih modern',
            ],
            [
                'nama_lengkap' => 'Gunawan Setiawan',
                'email' => 'gunawan.setiawan@example.com',
                'telepon' => '081234567896',
                'kategori_responden' => 'pemangku_kepentingan',
                'jenis_layanan' => 'kerjasama',
                'layanan_spesifik' => 'MoU Kerjasama',
                'tanggal_layanan' => '2024-02-15',
                'kemudahan_akses' => 5,
                'kecepatan_pelayanan' => 5,
                'keramahan_petugas' => 5,
                'kejelasan_informasi' => 5,
                'kualitas_hasil' => 5,
                'kepuasan_keseluruhan' => 5,
                'komentar_positif' => 'Proses kerjasama sangat profesional',
                'saran_perbaikan' => 'Pertahankan standar kerjasama yang tinggi',
            ],
            [
                'nama_lengkap' => 'Hesti Wulandari',
                'email' => 'hesti.wulandari@example.com',
                'telepon' => '081234567897',
                'kategori_responden' => 'mahasiswa',
                'program_studi' => 'teknik-mesin',
                'jenis_layanan' => 'akademik',
                'layanan_spesifik' => 'Pengisian Nilai',
                'tanggal_layanan' => '2024-02-20',
                'kemudahan_akses' => 3,
                'kecepatan_pelayanan' => 3,
                'keramahan_petugas' => 4,
                'kejelasan_informasi' => 3,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 3,
                'komentar_negatif' => 'Sistem pengisian nilai masih manual',
                'saran_perbaikan' => 'Otomatisasi sistem pengisian nilai',
            ],
            [
                'nama_lengkap' => 'Indra Kusuma',
                'email' => 'indra.kusuma@example.com',
                'telepon' => '081234567898',
                'kategori_responden' => 'dosen',
                'unit_kerja' => 'Bagian Kemahasiswaan',
                'jenis_layanan' => 'teknologi_informasi',
                'layanan_spesifik' => 'Maintenance Website',
                'tanggal_layanan' => '2024-02-25',
                'kemudahan_akses' => 4,
                'kecepatan_pelayanan' => 4,
                'keramahan_petugas' => 4,
                'kejelasan_informasi' => 4,
                'kualitas_hasil' => 4,
                'kepuasan_keseluruhan' => 4,
                'komentar_positif' => 'Tim IT responsif dalam maintenance',
                'saran_perbaikan' => 'Tambah fitur website yang lebih interaktif',
            ],
            [
                'nama_lengkap' => 'Joko Widodo',
                'email' => 'joko.widodo@example.com',
                'telepon' => '081234567899',
                'kategori_responden' => 'pemangku_kepentingan',
                'jenis_layanan' => 'lainnya',
                'layanan_spesifik' => 'Kunjungan Industri',
                'tanggal_layanan' => '2024-03-01',
                'kemudahan_akses' => 5,
                'kecepatan_pelayanan' => 5,
                'keramahan_petugas' => 5,
                'kejelasan_informasi' => 5,
                'kualitas_hasil' => 5,
                'kepuasan_keseluruhan' => 5,
                'komentar_positif' => 'Kunjungan industri sangat bermanfaat',
                'saran_perbaikan' => 'Tambah frekuensi kunjungan industri',
            ],
        ];

        foreach ($data as $item) {
            SurveyLayanan::create($item);
        }
    }
}
