<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TracerStudy;

class TracerStudySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nama_lengkap' => 'Ahmad Rizki',
                'nim' => '2021001',
                'program_studi' => 'teknik-informatika',
                'tahun_lulus' => 2023,
                'email' => 'ahmad.rizki@example.com',
                'telepon' => '081234567890',
                'ipk' => 3.75,
                'alamat' => 'Jl. Sudirman No. 123, Manado',
                'status_pekerjaan' => 'bekerja',
                'waktu_tunggu_kerja' => 3,
                'nama_perusahaan' => 'PT Tech Solutions Indonesia',
                'jabatan' => 'Software Developer',
                'gaji' => 4.5,
                'kesesuaian_bidang' => 'sangat_sesuai',
                'jenis_perusahaan' => 'Swasta Nasional',
                'bidang_pekerjaan' => 'IT/Software Development',
                'kepuasan_kurikulum' => 4,
                'relevansi_ilmu' => 5,
                'saran_pengembangan' => 'Kurikulum sudah sangat baik, perlu penambahan praktik industri',
                'saran_untuk_almamater' => 'Terus tingkatkan kerjasama dengan industri',
                'kompetensi_yang_dibutuhkan' => 'Programming, Database, Web Development',
                'kompetensi_yang_dimiliki' => 'Java, PHP, MySQL, Laravel',
                'rencana_kedepan' => 'Meningkatkan skill dan mengambil sertifikasi',
            ],
            [
                'nama_lengkap' => 'Sarah Putri',
                'nim' => '2021002',
                'program_studi' => 'teknik-sipil',
                'tahun_lulus' => 2023,
                'email' => 'sarah.putri@example.com',
                'telepon' => '081234567891',
                'ipk' => 3.80,
                'alamat' => 'Jl. Sam Ratulangi No. 45, Manado',
                'status_pekerjaan' => 'bekerja',
                'waktu_tunggu_kerja' => 2,
                'nama_perusahaan' => 'PT Konstruksi Maju',
                'jabatan' => 'Site Engineer',
                'gaji' => 3.8,
                'kesesuaian_bidang' => 'sesuai',
                'jenis_perusahaan' => 'Swasta Nasional',
                'bidang_pekerjaan' => 'Konstruksi',
                'kepuasan_kurikulum' => 4,
                'relevansi_ilmu' => 4,
                'saran_pengembangan' => 'Perlu lebih banyak praktik lapangan',
                'saran_untuk_almamater' => 'Tingkatkan fasilitas laboratorium',
                'kompetensi_yang_dibutuhkan' => 'AutoCAD, SAP2000, Manajemen Proyek',
                'kompetensi_yang_dimiliki' => 'AutoCAD, SAP2000, Microsoft Project',
                'rencana_kedepan' => 'Mengambil sertifikasi profesi',
            ],
            [
                'nama_lengkap' => 'Budi Santoso',
                'nim' => '2021003',
                'program_studi' => 'teknik-elektro',
                'tahun_lulus' => 2023,
                'email' => 'budi.santoso@example.com',
                'telepon' => '081234567892',
                'ipk' => 3.65,
                'alamat' => 'Jl. Piere Tendean No. 67, Manado',
                'status_pekerjaan' => 'wirausaha',
                'gaji' => 5.0,
                'bidang_pekerjaan' => 'Instalasi Listrik',
                'kepuasan_kurikulum' => 5,
                'relevansi_ilmu' => 5,
                'saran_pengembangan' => 'Kurikulum sangat membantu untuk berwirausaha',
                'saran_untuk_almamater' => 'Dukung mahasiswa untuk berwirausaha',
                'kompetensi_yang_dibutuhkan' => 'Instalasi Listrik, PLC, Maintenance',
                'kompetensi_yang_dimiliki' => 'Instalasi Listrik, PLC, AutoCAD',
                'rencana_kedepan' => 'Memperluas bisnis instalasi listrik',
            ],
            [
                'nama_lengkap' => 'Dewi Sartika',
                'nim' => '2021004',
                'program_studi' => 'arsitektur',
                'tahun_lulus' => 2023,
                'email' => 'dewi.sartika@example.com',
                'telepon' => '081234567893',
                'ipk' => 3.90,
                'alamat' => 'Jl. Wolter Monginsidi No. 89, Manado',
                'status_pekerjaan' => 'lanjut_studi',
                'kepuasan_kurikulum' => 5,
                'relevansi_ilmu' => 4,
                'saran_pengembangan' => 'Kurikulum sudah sangat baik untuk lanjut studi',
                'saran_untuk_almamater' => 'Tingkatkan kerjasama dengan universitas luar',
                'kompetensi_yang_dibutuhkan' => 'Research, Design, Presentation',
                'kompetensi_yang_dimiliki' => 'SketchUp, AutoCAD, 3D Max',
                'rencana_kedepan' => 'Melanjutkan S2 di bidang Arsitektur',
            ],
            [
                'nama_lengkap' => 'Eko Prasetyo',
                'nim' => '2021005',
                'program_studi' => 'teknik-mesin',
                'tahun_lulus' => 2023,
                'email' => 'eko.prasetyo@example.com',
                'telepon' => '081234567894',
                'ipk' => 3.55,
                'alamat' => 'Jl. Yos Sudarso No. 12, Manado',
                'status_pekerjaan' => 'belum_bekerja',
                'sumber_informasi_lowongan' => 'Internet',
                'metode_mencari_kerja' => 'Melalui Internet',
                'lamanya_mencari_kerja' => 6,
                'jumlah_lamaran' => 15,
                'jumlah_wawancara' => 3,
                'alasan_belum_bekerja' => 'Masih mencari posisi yang sesuai dengan bidang',
                'kepuasan_kurikulum' => 3,
                'relevansi_ilmu' => 3,
                'saran_pengembangan' => 'Perlu penyesuaian kurikulum dengan kebutuhan industri',
                'saran_untuk_almamater' => 'Bantu mahasiswa dalam penempatan kerja',
                'kompetensi_yang_dibutuhkan' => 'CAD/CAM, CNC, Maintenance',
                'kompetensi_yang_dimiliki' => 'AutoCAD, SolidWorks, Basic CNC',
                'rencana_kedepan' => 'Terus mencari pekerjaan yang sesuai',
            ],
            [
                'nama_lengkap' => 'Fitri Handayani',
                'nim' => '2021006',
                'program_studi' => 'teknik-informatika',
                'tahun_lulus' => 2022,
                'email' => 'fitri.handayani@example.com',
                'telepon' => '081234567895',
                'ipk' => 3.70,
                'alamat' => 'Jl. A.A. Maramis No. 34, Manado',
                'status_pekerjaan' => 'bekerja',
                'waktu_tunggu_kerja' => 4,
                'nama_perusahaan' => 'PT Digital Innovation',
                'jabatan' => 'Frontend Developer',
                'gaji' => 4.2,
                'kesesuaian_bidang' => 'sangat_sesuai',
                'jenis_perusahaan' => 'Swasta Nasional',
                'bidang_pekerjaan' => 'IT/Web Development',
                'kepuasan_kurikulum' => 4,
                'relevansi_ilmu' => 4,
                'saran_pengembangan' => 'Tambah materi React dan Vue.js',
                'saran_untuk_almamater' => 'Update kurikulum sesuai teknologi terbaru',
                'kompetensi_yang_dibutuhkan' => 'JavaScript, React, Vue.js, CSS',
                'kompetensi_yang_dimiliki' => 'HTML, CSS, JavaScript, Bootstrap',
                'rencana_kedepan' => 'Belajar framework modern dan meningkatkan skill',
            ],
            [
                'nama_lengkap' => 'Gunawan Setiawan',
                'nim' => '2021007',
                'program_studi' => 'teknik-sipil',
                'tahun_lulus' => 2022,
                'email' => 'gunawan.setiawan@example.com',
                'telepon' => '081234567896',
                'ipk' => 3.60,
                'alamat' => 'Jl. Bung Tomo No. 56, Manado',
                'status_pekerjaan' => 'bekerja',
                'waktu_tunggu_kerja' => 5,
                'nama_perusahaan' => 'Dinas Pekerjaan Umum',
                'jabatan' => 'Staff Perencanaan',
                'gaji' => 3.5,
                'kesesuaian_bidang' => 'sesuai',
                'jenis_perusahaan' => 'Pemerintah',
                'bidang_pekerjaan' => 'Pemerintahan',
                'kepuasan_kurikulum' => 4,
                'relevansi_ilmu' => 4,
                'saran_pengembangan' => 'Kurikulum sudah sesuai untuk kerja di pemerintahan',
                'saran_untuk_almamater' => 'Pertahankan kualitas pendidikan',
                'kompetensi_yang_dibutuhkan' => 'Perencanaan, AutoCAD, Microsoft Office',
                'kompetensi_yang_dimiliki' => 'AutoCAD, Microsoft Office, SAP2000',
                'rencana_kedepan' => 'Mengikuti tes CPNS dan meningkatkan kompetensi',
            ],
            [
                'nama_lengkap' => 'Hesti Wulandari',
                'nim' => '2021008',
                'program_studi' => 'arsitektur',
                'tahun_lulus' => 2022,
                'email' => 'hesti.wulandari@example.com',
                'telepon' => '081234567897',
                'ipk' => 3.85,
                'alamat' => 'Jl. Cokroaminoto No. 78, Manado',
                'status_pekerjaan' => 'wirausaha',
                'gaji' => 6.0,
                'bidang_pekerjaan' => 'Arsitektur & Interior Design',
                'kepuasan_kurikulum' => 5,
                'relevansi_ilmu' => 5,
                'saran_pengembangan' => 'Kurikulum sangat mendukung untuk berwirausaha',
                'saran_untuk_almamater' => 'Dukung mahasiswa untuk membuka studio arsitektur',
                'kompetensi_yang_dibutuhkan' => 'Design, Presentation, Business Management',
                'kompetensi_yang_dimiliki' => 'SketchUp, AutoCAD, 3D Max, Photoshop',
                'rencana_kedepan' => 'Memperluas studio dan mengambil proyek besar',
            ],
            [
                'nama_lengkap' => 'Indra Kusuma',
                'nim' => '2021009',
                'program_studi' => 'teknik-elektro',
                'tahun_lulus' => 2022,
                'email' => 'indra.kusuma@example.com',
                'telepon' => '081234567898',
                'ipk' => 3.50,
                'alamat' => 'Jl. Diponegoro No. 90, Manado',
                'status_pekerjaan' => 'bekerja',
                'waktu_tunggu_kerja' => 7,
                'nama_perusahaan' => 'PT PLN Persero',
                'jabatan' => 'Staff Maintenance',
                'gaji' => 4.8,
                'kesesuaian_bidang' => 'sangat_sesuai',
                'jenis_perusahaan' => 'BUMN',
                'bidang_pekerjaan' => 'Energi/Listrik',
                'kepuasan_kurikulum' => 5,
                'relevansi_ilmu' => 5,
                'saran_pengembangan' => 'Kurikulum sangat sesuai untuk kerja di PLN',
                'saran_untuk_almamater' => 'Jaga kerjasama dengan PLN',
                'kompetensi_yang_dibutuhkan' => 'Maintenance, PLC, SCADA',
                'kompetensi_yang_dimiliki' => 'PLC, SCADA, Maintenance, AutoCAD',
                'rencana_kedepan' => 'Mengambil sertifikasi dan naik jabatan',
            ],
            [
                'nama_lengkap' => 'Joko Widodo',
                'nim' => '2021010',
                'program_studi' => 'teknik-bangunan',
                'tahun_lulus' => 2022,
                'email' => 'joko.widodo@example.com',
                'telepon' => '081234567899',
                'ipk' => 3.45,
                'alamat' => 'Jl. Gatot Subroto No. 23, Manado',
                'status_pekerjaan' => 'belum_bekerja',
                'sumber_informasi_lowongan' => 'Teman',
                'metode_mencari_kerja' => 'Melalui Teman',
                'lamanya_mencari_kerja' => 8,
                'jumlah_lamaran' => 20,
                'jumlah_wawancara' => 5,
                'alasan_belum_bekerja' => 'Persaingan ketat dan pengalaman masih kurang',
                'kepuasan_kurikulum' => 3,
                'relevansi_ilmu' => 3,
                'saran_pengembangan' => 'Perlu lebih banyak praktik dan magang',
                'saran_untuk_almamater' => 'Bantu mahasiswa mendapatkan pengalaman kerja',
                'kompetensi_yang_dibutuhkan' => 'AutoCAD, SAP2000, Manajemen Proyek',
                'kompetensi_yang_dimiliki' => 'AutoCAD, Microsoft Office',
                'rencana_kedepan' => 'Mengambil kursus tambahan dan terus mencari kerja',
            ],
        ];

        foreach ($data as $item) {
            TracerStudy::create($item);
        }
    }
}
